name: Update Xray Configs Every 30 Min

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Xray updater
        run: bash ./scripts/run-xray.sh

      - name: Upload logs (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: xray-logs
          path: /tmp/xray-configs/
